In [31]:
#load all necessary libraries
import pandas as pd 
import numpy as np 
import scipy as scp
import sklearn

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn import metrics 
from sklearn.metrics import confusion_matrix

import matplotlib.pyplot as plt
import csv


import statsmodels.api as sm


df = pd.read_csv('log_190405_120032_KSWO.csv',header=2)
df = df.apply(pd.to_numeric, errors='coerce')
#df.head(10)
#df.columns
#df.info()
#df.describe()
#%matplotlib inline
#import matplotlib.pylab as plt
#plt.figure(figsize=(15,8)) 
#plt.plot(df['     Latitude'],df['    Longitude'])
#plt.show()
#import matplotlib.pylab as plt
#plt.figure(figsize=(15,8)) 
#plt.plot(df['     Latitude'],df['    Longitude'])
#read the dataset
#note that the csv file is space delimited
#abalone_df = pd.read_csv('log_190405_120032_KSWO.csv',  delimiter=' ') 
#balone_df.head()



AltMSL=df['  AltMSL'].value_counts()
GndSpd=df[' GndSpd'].value_counts()
IAS=df['    IAS'].value_counts()
VSpd=df['    VSpd'].value_counts()
Pitch=df['  Pitch'].value_counts()

y=[]


for i in range(len(df['  AltMSL'])):
    if i<=1711:
        y.append('NT')
        #print(i,y[i])
        
    elif 1711<i<=2081: #and i<2800:
        y.append('MN')
        #print(i,y[i])
    elif 2081<i<=2953:
        y.append('NT')
    #elif i<2287:
        #y.append('MN')
    elif 2953<i<=3218:
        y.append('MN')
    elif 3218<i<=3431:
        y.append('NT')    
    elif 3431<i<=3559:
        y.append('MN') 
    elif 3559<i<=3706:
        y.append('NT')
    elif 3706<i<=3782:
        y.append('MN') 
    elif 3782<i<=3908:
        y.append('NT')  
    elif 3908<i<=4024:
        y.append('MN') 
    elif 4024<i<=4156:
        y.append('NT') 
    elif 4156<i<=4248:
        y.append('MN') 
    elif 4248<i<=4358:
        y.append('NT')
    else:
        y.append('LD')
#Phases=y.value_counts()        
        
print(AltMSL)
#print(GndSpd)
#print(VSpd)
#print(Pitch)
#print(y)

955.1     22
954.9     14
954.7     10
984.9     10
954.8     10
          ..
4456.5     1
3569.1     1
2477.4     1
1535.8     1
944.0      1
Name:   AltMSL, Length: 3657, dtype: int64


In [32]:
#Create training and test datasets
#CLASS was recoded into SIZE_CLASS to change from string to integer
#CLASS needs to be dropped
X = df.drop(['  Lcl Date',' Lcl Time',' UTCOfst',' AtvWpt','     Latitude','    Longitude','    AltB',' BaroA','   OAT','   Roll','  LatAc',' NormAc','   HDG','   TRK',' volt1',' volt2','  amp1','  amp2','  FQtyL','  FQtyR',' E1 FFlow',' E1 OilT',' E1 OilP',' E1 RPM',' E1 CHT1',' E1 CHT2',' E1 CHT3',' E1 CHT4',' E1 EGT1',' E1 EGT2',' E1 EGT3',' E1 EGT4','  AltGPS',' TAS',' HSIS','    CRS','   NAV1','   NAV2','    COM1','    COM2','   HCDI','   VCDI',' WndSpd',' WndDr',' WptDst',' WptBrg',' MagVar',' AfcsOn',' RollM',' PitchM',' RollC',' PichC',' VSpdG',' GPSfix','  HAL','   VAL',' HPLwas',' HPLfd',' VPLwas'], axis=1) 
print(list(X.columns.values)) 


['  AltMSL', '    IAS', ' GndSpd', '    VSpd', '  Pitch']


In [33]:
#len(df['  AltMSL'])

In [34]:

        
    #elif i>2100 and i<2800:
       # y[i]='TakeOff'



#y = df['Maneuver']



X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, test_size = 0.20, random_state = 5)
print(X_train.shape)
print(X_test.shape)

#print(y_test.shape)

(3720, 5)
(930, 5)


In [35]:
model1 = LogisticRegression(random_state=0, multi_class='multinomial', penalty='none', solver='newton-cg').fit(X_train, y_train)
preds = model1.predict(X_test)

#print the tunable parameters (They were not tuned in this example, everything kept as default)
params = model1.get_params()
print(params)


{'C': 1.0, 'class_weight': None, 'dual': False, 'fit_intercept': True, 'intercept_scaling': 1, 'l1_ratio': None, 'max_iter': 100, 'multi_class': 'multinomial', 'n_jobs': None, 'penalty': 'none', 'random_state': 0, 'solver': 'newton-cg', 'tol': 0.0001, 'verbose': 0, 'warm_start': False}


In [36]:
#Print model parameters
print('Intercept: \n', model1.intercept_)
print('Coefficients: \n', model1.coef_)

Intercept: 
 [ 1.80534043 -1.55054475 -0.25479568]
Coefficients: 
 [[-0.00302958 -0.14818653  0.16359693 -0.00048357 -0.18372669]
 [ 0.00135954  0.10797042 -0.1154043  -0.00321118  0.0895209 ]
 [ 0.00167003  0.0402161  -0.04819264  0.00369474  0.0942058 ]]


In [37]:
#Calculate odds ratio estimates
import numpy as np
np.exp(model1.coef_)


array([[0.99697501, 0.86227026, 1.17773951, 0.99951655, 0.83216321],
       [1.00136046, 1.1140148 , 0.89100584, 0.99679397, 1.09365019],
       [1.00167143, 1.04103572, 0.9529502 , 1.00370158, 1.09878585]])

In [38]:
#Use statsmodels to assess variables

logit_model=sm.MNLogit(y_train,sm.add_constant(X_train))
logit_model
result=logit_model.fit()
stats1=result.summary()
stats2=result.summary2()
print(stats1)
print(stats2)

Optimization terminated successfully.
         Current function value: 0.414019
         Iterations 10
                          MNLogit Regression Results                          
Dep. Variable:                      y   No. Observations:                 3720
Model:                        MNLogit   Df Residuals:                     3708
Method:                           MLE   Df Model:                           10
Date:                Fri, 29 Jul 2022   Pseudo R-squ.:                  0.4460
Time:                        23:44:25   Log-Likelihood:                -1540.2
converged:                       True   LL-Null:                       -2779.9
Covariance Type:            nonrobust   LLR p-value:                     0.000
      y=MN       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -3.3559      0.461     -7.277      0.000      -4.260      -2.452
  AltMSL       0.0044      0

In [39]:
#Create a confusion matrix
#y_test as first argument and the preds as second argument 
confusion_matrix(y_test, preds)

#array([[ 88,  34, 135],
  #     [ 11, 223,  28],
   #    [ 88,  63, 159]])

#transform confusion matrix into array
#the matrix is stored in a vaiable called confmtrx
confmtrx = np.array(confusion_matrix(y_test, preds))
#Create DataFrame from confmtrx array 
#rows for test: Male, Female, Infant designation as index 
#columns for preds: male, predicted_female, predicted_infant as column

pd.DataFrame(confmtrx, index=['NT','LD','MN'],
columns=['predicted_NT','predicted_LD','predicted_MN'])#'predicted_MN'])

predicted_NT  predicted_LD  predicted_MN
NT            13            16            38
LD             1           129            72
MN            12            33           616

In [40]:
#Accuracy statistics

print('Accuracy Score:', metrics.accuracy_score(y_test, preds))  

#Create classification report
class_report=classification_report(y_test, preds)
print(class_report)

Accuracy Score: 0.8150537634408602
              precision    recall  f1-score   support

          LD       0.50      0.19      0.28        67
          MN       0.72      0.64      0.68       202
          NT       0.85      0.93      0.89       661

    accuracy                           0.82       930
   macro avg       0.69      0.59      0.62       930
weighted avg       0.80      0.82      0.80       930

